### ISSUE TITLE
EventIDs typed as string causing matching errors

### ISSUE THREAD

**Issue by thomaspatzke** [SigmaHQ/pySigma-backend-elasticsearch#109]
Good morning,

there is a similar issue regarding the field mapping of keyword fields which contain numerical data (e.g. event.code) using the `ESQL` backend:
Searching for 
```yaml
detection:
  condition: selection
  selection:
    EventID:
      # - 1
      - 4688
```
converted by `sigma convert rules/test-rule.yaml  -t esql -p ecs_windows` results in `... | where event.code==4688`, which causes the error 
`first argument of [event.code==4688] is [keyword] so second argument must also be [keyword] but was [integer]` because event.code is mapped as a keyword field in ecs.

Currently I´ve solved this issue by the following pipeline:
```yaml
transformations:
- id: change_field_mapping_to_str
  type: convert_type
  target_type: str
  field_name_conditions:
    - type: include_fields
      fields: 
        - event.id
        - event.code
```
Applying this pipeline converts the rule into `... | where event.code=="4688"` which runs without problems

Since most users probably except that as soon as they apply the ecs_windows pipeline, the query should work without the need of an extra pipeline in an environment with ecs, maybe it would be better to solve this problem also directly in the code?

_Originally posted by @Mat0vu in https://github.com/SigmaHQ/pySigma-backend-elasticsearch/issues/103#issuecomment-2530688783_
