### ISSUE TITLE
ES|QL transform pipeline issues with correlation rules

### ISSUE THREAD

**Issue by ScioShield** [SigmaHQ/pySigma-backend-elasticsearch#125]
Versions
```bash
$ uname -a
Linux tartarus-kali 6.12.13-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.12.13-1kali1 (2025-02-11) x86_64 GNU/Linux

$ sigma version                                            
1.0.5 (online pypi.org: 1.0.5)

$ python3 --version
Python 3.13.2
```

Pull #77 has introduced/regressed an issue when dealing with lists of indices in ES\|QL (a single rule file with multiple definitions as needed to do correlation rules in one file doesn't work as expected, normal single rule files are working as expected) it produces the same issue mentioned in #72 namely a transform like the below will produce:

```bash
sigma convert -t esql -p transform.yml  pfsense_port_scan.yml
```
```sql
from ['logs-test1-*', 'logs-test2-*'] metadata _id, _index, _version | where event.dataset=="pfsense.log" and event.provider=="filterlog" and event.action=="block" and (cidr_match(destination.ip, "10.0.0.0/8") or cidr_match(destination.ip, "172.16.0.0/12") or cidr_match(destination.ip, "192.168.0.0/16"))
| eval timebucket=date_trunc(5minutes, @timestamp) | stats value_count=count_distinct(destination.port) by timebucket, source.ip, destination.ip, observer.name
| where value_count >= 1000
```

I suspect line 290 of [elasticsearch_esql.py](https://github.com/SigmaHQ/pySigma-backend-elasticsearch/blob/e0446e9b17052dde29cd6566192bb226adcc6482/sigma/backends/elasticsearch/elasticsearch_esql.py#L290) doesn't handle nested lists properly.

My Python foo isn't strong enough to fix this issue myself. :)

Transformation pipeline:
```
transformations:
  - id: set_state_index
    type: set_state
    key: index
    val:
      - logs-test1-*
      - logs-test2-*
    rule_conditions:
      - type: logsource
        product: pfsense
```

Sigma rule:
```
title: Base Rule - pfSense Port Scan Activity
id: f7ac5b00-1e2d-4b5e-8ecc-53f81cf3a5ba
status: experimental
name: base_rule_pfsense_port_scan
description: Base Rule to filter for blocked network events going to RFC 1918 addresses
date: 2025/03/17
tags:
  - attack.reconnaissance
  - attack.t1595.001
logsource:
  product: pfsense
  service: filterlog
  category: firewall
detection:
    selection:
      event.dataset: "pfsense.log"
      event.provider: "filterlog"
      event.action: "block"
    cidr_expression:
        - destination.ip|cidr: 10.0.0.0/8
        - destination.ip|cidr: 172.16.0.0/12
        - destination.ip|cidr: 192.168.0.0/16
    condition: selection and cidr_expression
level: informational
---
title: pfSense Port Scan Activity
id: 0c61e4ef-b201-4f9c-847f-f6ec9c7c3aaa
status: experimental
name: pfsense_port_scan
description: |
    Correlation rule to detect blocked network events from a single source to a single destination via a single observer on over 1000 unique ports over 5 minutes
date: 2025/03/17
tags:
  - attack.reconnaissance
  - attack.t1595.001
correlation:
    type: value_count
    rules: 
    - base_rule_pfsense_port_scan
    group-by:
        - source.ip
        - destination.ip
        - observer.name
    timespan: 5m
    condition:
        gte: 1000
        field: destination.port
falsepositives: 
  - Likely
  - Internal vulnerability scanners such as Nessus do port scanning to verify what ports are open on the target
level: low
```
Expected results
```sql
from logs-test1-*,logs-test2-* metadata _id, _index, _version | where event.dataset=="pfsense.log" and event.provider=="filterlog" and event.action=="block" and (cidr_match(destination.ip, "10.0.0.0/8") or cidr_match(destination.ip, "172.16.0.0/12") or cidr_match(destination.ip, "192.168.0.0/16"))
| eval timebucket=date_trunc(5minutes, @timestamp) | stats value_count=count_distinct(destination.port) by timebucket, source.ip, destination.ip, observer.name
| where value_count >= 1000
```
Actual results
```sql
from ['logs-test1-*', 'logs-test2-*'] metadata _id, _index, _version | where event.dataset=="pfsense.log" and event.provider=="filterlog" and event.action=="block" and (cidr_match(destination.ip, "10.0.0.0/8") or cidr_match(destination.ip, "172.16.0.0/12") or cidr_match(destination.ip, "192.168.0.0/16"))
| eval timebucket=date_trunc(5minutes, @timestamp) | stats value_count=count_distinct(destination.port) by timebucket, source.ip, destination.ip, observer.name
| where value_count >= 1000
```
Any questions give me a shout!
