### ISSUE TITLE
Logsource leads to incorrect Lucene query

### ISSUE THREAD

**Issue by fbausch** [SigmaHQ/pySigma-backend-elasticsearch#128]
Hi,

I have issues with, for example, the following Sigma rule when converting it to Lucene query for Elastic:

```yml
title: Sysmon Configuration Change
id: 8ac03a65-6c84-4116-acad-dc1558ff7a77
status: test
description: Detects a Sysmon configuration change, which could be the result of a legitimate reconfiguration or someone trying manipulate the configuration
references:
    - https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
author: frack113
date: 2022-01-12
tags:
    - attack.defense-evasion
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 16
    # To avoid FP just add
    # filter:
    #      ConfigurationFileHash: 'SHA256=The_Hash_Of_Your_Valid_Config_XML'
    # condition: selection and not filter
    condition: selection
falsepositives:
    - Legitimate administrative action
level: medium
```

Sigma converts it as follows:

```
sigma convert -t lucene -p ecs_windows rules/windows/sysmon/sysmon_config_modification.yml
Parsing Sigma rules  [####################################]  100%
winlog.channel:Microsoft\-Windows\-Sysmon\/Operational AND event.code:16
```

The issue here is that Lucene in Elastic will even match when the `winlog.channel` is `Microsoft-Windows-SomeThingElse/Operational`.

The issue would not arise if the query were:

```
winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational" AND event.code:16
```
