### ISSUE TITLE
Incorrect conversion of > character in sigma rule for Elastic/ECS Windows type

### ISSUE THREAD

**Issue by canilc** [SigmaHQ/pySigma-backend-elasticsearch#26]
Rule source:

```yml
title: Redirect Output in CommandLine
id: 4f4eaa9f-5ad4-410c-a4be-bc6132b0175a
status: experimental
description: Detects use of redirection character ">" to redicrect information in commandline
references:
    - https://ss64.com/nt/syntax-redirection.html
author: frack113
date: 2022/01/22
modified: 2023/01/10
tags:
    - attack.discovery
    - attack.t1082
logsource:
    category: process_creation
    product: windows
detection:
    selection_cmd:
        - OriginalFileName: 'Cmd.Exe'
        - Image|endswith: '\cmd.exe'
    selection_cli:
        CommandLine|contains: '>'
    filter_idm_extension:
        CommandLine|contains:
            - 'C:\Program Files (x86)\Internet Download Manager\IDMMsgHost.exe'
            - 'chrome-extension://'
            - '\\.\pipe\chrome.nativeMessaging'
    condition: all of selection_* and not 1 of filter_*
falsepositives:
    - Internet Download Manager extensions use named pipes and redirection via CLI. Filter it out if you use it in your environment
level: low
```

Full converted output is:

```
((process.pe.original_file_name:Cmd.Exe OR process.executable:*\\cmd.exe) AND process.command_line:**) AND (NOT (process.command_line:(*C\:\\Program\ Files\ \(x86\)\\Internet\ Download\ Manager\\IDMMsgHost.exe* OR *chrome\-extension\:\/\/* OR *\\.\\pipe\\chrome.nativeMessaging*)))
```

As seen in the output `CommandLine|contains: '>'` is converted to `process.command_line:**`, likely caused by an escaping or grammar problem?

Command used to convert:

```sh
sigma convert -t elasticsearch -p ecs_windows ./rules/windows/process_creation/proc_creation_win_cmd_redirect.yml
```
