### ISSUE TITLE
Lucene Rule Generation Quotation Mark Issue

### ISSUE THREAD

**Issue by LucaKuechler** [SigmaHQ/pySigma-backend-elasticsearch#36]
### Lucene Rule Generation Quotation Mark Issue

When a selection item contains a blank space, the Lucene rule will be 
surrounded by quotation marks, which seems like an invalid syntax.

### Description

I tried converting this rule by using the command below:
```yaml
title: Xmrig
status: experimental
description: Detect Xmrig
references:
  - https://google.com
author: unknown
date: 2023/08/16
modified: 2023/08/16
tags:
  - attack.placeholder
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    CommandLine|contains:
      - 'cn/half --cpu-priority'
      - '--cpu-priority 1'
  condition: selection
level: critical
```

```bash
sigma convert -t lucene -p ecs_windows rule.yml
```

The generated rule looked like this:
```
process.command_line:("*cn\/half\ \-\-cpu\-priority*" OR "*\-\-cpu\-priority\ 1*")
```
My expectation would be to not have those quotation marks. It should look like:
```
process.command_line:(*cn\/half\ \-\-cpu\-priority* OR *\-\-cpu\-priority\ 1*)
```

I tested both versions inside my local Elasticsearch instance and the one with quotation mark didn't show any results. This is due to the nature of Lucene query language, which interprets the quotation marks as normal character. This behavior is also mentioned inside their [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/query-dsl-query-string-query.html#query-string-syntax).
 

### Environment

- **Elasticsearch Version**:  8
- **pySigma-backend-elasticsearch Version**: 1.0.9
- **Python Version**:  3.10

### Possible Fix

- When I change the variable ` str_quote: ClassVar[str] = '"'` to ` str_quote: ClassVar[str] = ''`  then it works. But not sure if it breaks other things.
