### ISSUE TITLE
Wrong network direction values

### ISSUE THREAD

**Issue by cospirho** [SigmaHQ/pySigma-backend-elasticsearch#57]
The [default winlogbeat sysmon pipeline](https://github.com/elastic/beats/blob/b4ff53ce2b2d0037faa58d88afa2afbdc82d3033/x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml#L691) values for the network direction are changed from true/false to egress/ingress, and winlog.event_data.Initiated is removed (changed to network.direction). This backend will output the values of true/false

```yaml
detection:
    selection:
        Initiated: 'true'
        Image|endswith: '\msiexec.exe'
        DestinationPort:
            - 80
            - 443
```

I'm not sure what the best way to handle this would be....also not 100% sure if it's an issue with this repo, the rules, both, or neither. I didn't see 'Initiated' anywhere in the sigma rule taxonomy specification.
