### ISSUE TITLE
Convert esql correlation rule fail no attribute get_conversion_states

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/pySigma-backend-elasticsearch#59]
I get an error every time I try to convert a correlation rule 
`sigma convert -t esql -p sysmon win_susp_failed_hidden_share_mount2.yaml`
```python
for state in rule_reference.rule.get_conversion_states()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SigmaRule' object has no attribute 'get_conversion_states'. Did you mean: 'get_conversion_result'?
```
the rule
```yaml
title: Failed Mounting of Hidden Share
name: sigma_rule_mounting_hidden
logsource:
    product: windows
    service: smbclient-security
detection:
    selection:
        EventID: 31010
        ShareName|endswith: '$'
    condition: selection
---
title: Failed Mounting of Hidden Share
author: Fabian Franz
correlation:
    type: event_count
    rules:
        - sigma_rule_mounting_hidden
    group-by:
        - Computer
    timespan: 1m
    condition:
        gt: 10
level: medium
```

With splunk
```bash
EventID=31010 ShareName="*$"
| bin _time span=1m
| stats count as event_count by _time Computer
| search event_count > 10
```
