### ISSUE TITLE
Conversion of empty strings in grouped OR expression

### ISSUE THREAD

**Issue by canilc** [SigmaHQ/pySigma-backend-elasticsearch#8]
Rule source:

```
title: Rundll32 Execution Without DLL File
id: c3a99af4-35a9-4668-879e-c09aeb4f2bdf
status: experimental
description: Detects the execution of rundll32 with a command line that doesn't contain a .dll file
references:
    - https://twitter.com/mrd0x/status/1481630810495139841?s=12
author: Tim Shelton, Florian Roth, Yassine Oukessou (fix + fp)
date: 2022/01/13
modified: 2022/07/27
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: '\rundll32.exe'
    filter_empty:
        CommandLine: null
    filter:
        - CommandLine|contains: '.dll'
        - CommandLine: ''
    filter_iexplorer:
        ParentImage|endswith: ':\Program Files\Internet Explorer\iexplore.exe'
        CommandLine|contains: '.cpl'
    filter_msiexec_syswow64:
        ParentImage|endswith: ':\Windows\SysWOW64\msiexec.exe'
        ParentCommandLine|startswith: 'C:\Windows\syswow64\MsiExec.exe -Embedding'
    filter_msiexec_system32:
        ParentImage|endswith: ':\Windows\System32\msiexec.exe'
        ParentCommandLine|startswith: 'C:\Windows\system32\MsiExec.exe -Embedding'
    filter_splunk_ufw:
        ParentImage|endswith: ':\Windows\System32\cmd.exe'
        ParentCommandLine|contains: ' C:\Program Files\SplunkUniversalForwarder\'
    filter_localserver_fp:
        CommandLine|contains: ' -localserver '
    condition: selection and not 1 of filter*
fields:
    - Image
    - CommandLine
falsepositives:
    - Unknown
level: high
```

Conversion of `- CommandLine: ''` filter turns into `(process.command_line:(*.dll* OR ))` which cannot be interpreted by Elastic Search. For empty expressions `""` should be used instead.

Full converted output is:
```
process.executable:*\\\\rundll32.exe AND (NOT (NOT _exists_:process.command_line OR (process.command_line:(*.dll* OR )) OR (process.parent.executable:*\\:\\\\Program\\ Files\\\\Internet\\ Explorer\\\\iexplore.exe AND process.command_line:*.cpl*) OR (process.parent.executable:*\\:\\\\Windows\\\\SysWOW64\\\\msiexec.exe AND process.parent.command_line:C\\:\\\\Windows\\\\syswow64\\\\MsiExec.exe\\ \\-Embedding*) OR (process.parent.executable:*\\:\\\\Windows\\\\System32\\\\msiexec.exe AND process.parent.command_line:C\\:\\\\Windows\\\\system32\\\\MsiExec.exe\\ \\-Embedding*) OR (process.parent.executable:*\\:\\\\Windows\\\\System32\\\\cmd.exe AND process.parent.command_line:*\\ C\\:\\\\Program\\ Files\\\\SplunkUniversalForwarder\\\\*) OR process.command_line:*\\ \\-localserver\\ *))
```

Command used to convert:

`sigma convert -t elasticsearch -p ecs_windows ./rules/windows/process_creation/proc_creation_win_run_executable_invalid_extension.yml`
